import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import logo from "../public/DOVLogo.png";
import { SocialIcon } from "react-social-icons";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className=" margin-auto">
          <div className="flex justify-center  ">
            <div className="w-full overflow-hidden  items-center flex flex-col text-center">
              <div className="w-[150px] h-[150px]  rounded-full">
                <Image src={logo} className="rounded-full"></Image>
              </div>
              <div className="text-5xl pt-[30px]  font-black">$DOV</div>
              <div className="text-[#FF1640] text-[24px] font-black pb-16">
                Doge Original Vision
              </div>
              <div className="flex w-[300px] md:w-[500px] justify-between md:justify-around">
                <ConnectButton.Custom>
                  {({
                    account,
                    chain,
                    openAccountModal,
                    openChainModal,
                    openConnectModal,
                    authenticationStatus,
                    mounted,
                  }) => {
                    // Note: If your app doesn't use authentication, you
                    // can remove all 'authenticationStatus' checks
                    const ready = mounted && authenticationStatus !== "loading";
                    const connected =
                      ready &&
                      account &&
                      chain &&
                      (!authenticationStatus ||
                        authenticationStatus === "authenticated");

                    return (
                      <div
                        {...(!ready && {
                          "aria-hidden": true,
                          style: {
                            opacity: 0,
                            pointerEvents: "none",
                            userSelect: "none",
                          },
                        })}
                      >
                        {(() => {
                          if (!connected) {
                            return (
                              <button
                                className="bg-[#ffc700] px-6 md:px-14 font-bold py-4 rounded-lg text-black easy-in-out duration-300 "
                                onClick={openConnectModal}
                                type="button"
                              >
                                CONNECT
                              </button>
                            );
                          }

                          if (chain.unsupported) {
                            return (
                              <button
                                className="bg-[#ffc700] px-6 md:px-14 font-bold py-4 rounded-lg text-black easy-in-out duration-300 "
                                onClick={openChainModal}
                                type="button"
                              >
                                Wrong network
                              </button>
                            );
                          }

                          return (
                            <div
                              style={{ display: "flex", gap: 12 }}
                              className="bg-[#ffc700] px-2  font-bold py-4 rounded-lg text-black easy-in-out duration-300 "
                            >
                              <button
                                onClick={openChainModal}
                                style={{
                                  display: "flex",
                                  alignItems: "center",
                                }}
                                type="button"
                              >
                                {chain.hasIcon && (
                                  <div
                                    style={{
                                      background: chain.iconBackground,
                                      width: 12,
                                      height: 12,
                                      borderRadius: 999,
                                      overflow: "hidden",
                                      marginRight: 4,
                                    }}
                                  >
                                    {chain.iconUrl && (
                                      <img
                                        alt={chain.name ?? "Chain icon"}
                                        src={chain.iconUrl}
                                        style={{ width: 12, height: 12 }}
                                      />
                                    )}
                                  </div>
                                )}
                                {chain.name}
                              </button>

                              <button onClick={openAccountModal} type="button">
                                {account.displayName}
                                {account.displayBalance
                                  ? ` (${account.displayBalance})`
                                  : ""}
                              </button>
                            </div>
                          );
                        })()}
                      </div>
                    );
                  }}
                </ConnectButton.Custom>{" "}
                <button className="ease-in-out duration-300 w-full max-w-[130px] md:max-w-[200px] py-2 flex items-center  justify-center hover:bg-[#ffffff40] hover:text-[#191924] bg-[#191924] text-[#ffffff40] font-bold text-xl rounded-lg">
                  CLAIM
                </button>
              </div>
              <div className="grid grid-cols-3 gap-8 mt-12">
                <SocialIcon network="twitter" fgColor="white"></SocialIcon>
                <SocialIcon network="telegram" fgColor="white"></SocialIcon>
                <SocialIcon network="discord" fgColor="white"></SocialIcon>
                <SocialIcon network="reddit" fgColor="white"></SocialIcon>
                <SocialIcon network="tiktok" fgColor="white"></SocialIcon>
                <SocialIcon network="youtube" fgColor="white"></SocialIcon>
              </div>
              <div className="rounded-lg w-full md:w-1/3 bg-[#191924] p-8 mt-24 text-start font-extralight">
                <div className="text-4xl pb-8 font-bold">The $DOV Purpose</div>
                Deep in the shadows of the cryptocurrency world, a promise was
                made. A promise that was meant to be a beacon of hope for
                everybody regardless of status. $SHIB began as a dream to create
                a coin for the people, by the people, and without the imbalanced
                power structure of elites who leave the people enslaved to their
                dumping, project after project. The emergence of meme tokens
                promised a new and exciting vision of egalitarian access to
                wealth and community. However, as time passed, whispers began to
                spread amongst the early supporters of Shiba Inu who were there
                from the inception. Whispers that brought doubt, whispers that
                spoke of darkness.<br></br>
                <br></br> With each new block mined, the coin’s path began to
                stray further and further from its core mission to bring joy and
                give hope to anyone regardless of pedigree or baggage. The goal
                of Shiba was to be the new dawn for so many who were suffering
                in the darkness; unfortunately the true nature of the enigmatic
                leader behind the coin wouldn't allow this dream to be realized.
                <br></br>
                <br></br> A dark force took control of $SHIB, using obfuscation
                to hide his real intentions. Rumor has it that this dark force
                held a majority stake in Shiba through thousands of wallets that
                were under his control. Ryoshi abandoned his army and failed to
                ship a meaningful technology roadmap, which turned Shiba into a
                perpetual bear market nightmare for those who had remained loyal
                to its original vision and faithful to the Ryoshi cult.<br></br>
                <br></br> A key contributor to the ideation and creation of
                Shiba, known only as The Dogfather, never received any
                recognition or reward for his vital contributions from Ryoshi.
                <br></br>
                <br></br>
                The Dogfather was a key architect in helping Ryoshi develop the
                community that became Shiba. However, Ryoshi and his two evil
                henchmen didn’t believe in the altruistic goals of the Dogfather
                and seized the opportunity to usurp power and take control of
                the project.<br></br>
                <br></br> It is due to this sacrifice that the Dogfather will
                receive a small amount of $DOV tokens, to pay homage for his
                great contributions early on in the project. For years, the
                truth was hidden deep in the blockchain and that anonymity
                allowed Ryoshi to play the role of benevolent leader who
                sympathized with the rest of his cohorts, while eventually
                abandoning his army and failing to deliver the Shibarium. Ryoshi
                and his henchmen erased all of their social media and digital
                footprint in hopes of remaining hidden with their buckets of
                $SHIB. The former friends near them understand how Ryoshi and
                his two lackeys did not reciprocate back all the good deeds paid
                forward to them from the many good samaritans in the land of
                cryptocurrencies.<br></br>
                <br></br> But now, from the ashes of this once great dream
                arises a new people’s champion who will return power back to
                those who stayed loyal to the core tenets that Shiba was founded
                on.<br></br>
                <br></br> Shib Original Vision ($SOV) fixes the corruption
                behind $SHIB by fairly distributing $SOV to those who believe in
                the genuine Shiba Inu community. $SOV was developed by true
                devotees in the dream that was once Shiba. They intend on $DOV
                to be distributed in a manner that is not only equitable and
                righteous but also transparent.<br></br>
                <br></br> In order to establish a truly equitable community, an
                equivalent amount of $SOV will be dispersed among Shiba Inu
                holders who have been active on-chain in the last 6 months days.
                277,000 $SHIB wallets will be eligible for $SOV, making it one
                of the largest airdrops in crypto history. For holders that have
                $SHIB on centralized exchanges, a dedicated portion of the token
                metrics will be reserved for CEX airdrop and listing
                negotiations, governed by 59 members of the Inu Economic Forum,
                which is made up of Karma DAO OGs.<br></br>
                <br></br> Karma DAO members directly helped with the execution,
                ideation, support and marketing of Shiba Inu in the early days
                prior to Ryoshi’s duplicitous acts against the $SHIB community.
                A portion of the tokens will be granted to Karma DAO as well as
                The Dogfather to pay homage for their contributions early on in
                the project.<br></br>
                <br></br> Distributing $SOV tokens to the people is the right
                way to honor the Shiba Inu community. Shiba Inu is not lost –
                the community can be great again and deserves to be given a
                second chance with a coin that has a more fair token
                distribution than Ryoshi’s Shiba Inu.<br></br>
                <br></br> It is time we make the Shiba Inu community all it was
                envisioned to be: equal opportunity for everyone. No whales and
                rich people playing games, deceiving the people at the bottom.
                In a nutshell, plain old transparency and fairness. Shibarium
                led the $SHIB community astray. It's time for $SOV.<br></br>
                <br></br> The $SOV team vows to not let the $SHIB army down this
                time. The $SHIB holders have had enough. $SOV is here, and the
                bear market pain is almost over.<br></br>
                <br></br> The $SOV coin icon depicts a Shiba Inu rising from
                ashes like a phoenix because from the embers of this once great
                dream $SOV will resurge stronger and more dedicated than ever to
                the mission.<br></br>
                <br></br>
                The $SOV team respects BitBoy for bringing light to darkness,
                and helping the army find its new way after Ryoshi. May a new
                era begin with $SOV.<br></br>
                <br></br> May we see brighter days, positive changes and greater
                evolution to the Shiba Inu story.<br></br>
                <br></br> With love, understanding and new hope for all,
                <br></br> The $SOV team
              </div>
              <div className="rounded-lg w-full md:w-1/3 bg-[#191924] p-8 mt-24 text-start font-extralight">
                <div className="text-4xl pb-8 font-bold">
                  $DOV Token Metrics
                </div>
                <div className="pb-8 ">
                  1,000,000,000,000,000 Total $DOV Supply
                </div>
                <div className="flex items-start justify-between">
                  <div className="flex">
                    <div className="w-3 h-3 rounded-sm bg-red-600 mt-[7px] "></div>
                    <div className="pl-3">%80</div>
                  </div>

                  <div className="w-2/3 flex flex-col">
                    <div className="ml-4 font-semibold">
                      $DOGE Community Airdrop
                    </div>
                    <div className="pl-4">
                      Airdrop to DOGE Inu Community ($DOGE): An equal amount of
                      $SOV is claimed for each $DOGE wallets that hold 1 $DOGE
                      and have been active in past 6 months onchain from Block
                      16860452. Airdrop claim window is open for 30 days
                    </div>
                  </div>
                </div>
                <div className="flex items-start justify-between pt-8">
                  <div className="flex">
                    <div className="w-3 h-3 rounded-sm bg-[#7CFB5C] mt-[7px] "></div>
                    <div className="pl-3">%0.5</div>
                  </div>

                  <div className="w-2/3 flex flex-col">
                    <div className="ml-4 font-semibold">The Dogfather</div>
                    <div className="pl-4">
                      Airdrop to The Dogfather, the secret co-creator of $DOGE
                      ideas but was rugged by Ryoshi
                    </div>
                  </div>
                </div>
                <div className="flex items-start justify-between pt-8">
                  <div className="flex">
                    <div className="w-3 h-3 rounded-sm bg-[#7b6ffc] mt-[7px] "></div>
                    <div className="pl-3">%5.5</div>
                  </div>

                  <div className="w-2/3 flex flex-col">
                    <div className="ml-4 font-semibold">Karma DAO Airdrop</div>
                    <div className="pl-4">
                      Airdrop to Karma DAO members, including a bonus airdrop to
                      Karma members that contributed to initial $DOV liquidity
                      pools
                    </div>
                  </div>
                </div>
                <div className="flex items-start justify-between pt-8">
                  <div className="flex">
                    <div className="w-3 h-3 rounded-sm bg-[#FFC700] mt-[7px] "></div>
                    <div className="pl-3">%6.5</div>
                  </div>

                  <div className="w-2/3 flex flex-col">
                    <div className="ml-4 font-semibold">
                      Liquidity Pools for Dexes
                    </div>
                    <div className="pl-4">
                      Tokens used for bridges and potential future DEX Liquidity
                      Pools{" "}
                    </div>
                  </div>
                </div>
                <div className="flex items-start justify-between pt-8">
                  <div className="flex">
                    <div className="w-3 h-3 rounded-sm bg-[#4a99e9] mt-[7px] "></div>
                    <div className="pl-3">%7.5</div>
                  </div>

                  <div className="w-2/3 flex flex-col">
                    <div className="ml-4 font-semibold">
                      CEX Listings and CEX Airdrops
                    </div>
                    <div className="pl-4">
                      Tokens reserved for CEX listings, CEX listing fees and CEX
                      airdrops, governed by leaders in Karma DAO called the Inu
                      Economic Forum{" "}
                    </div>
                  </div>
                </div>
                <div className="w-full flex justify-center mt-12">
                  <Image src={logo} width={200} className="rounded-full"></Image>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
